adds full hero
svoits/mimino-himars pull request #19
Opened 2023-01-29 08:26 UTC by cutestsun

2023-01-29 15:34 UTC, svoits requested changes
please also edit icons in the same way as in the header

2023-01-29 15:34 UTC, svoits commented on src/partials/hero.html
> +          >Україна, м.&nbspПолтава, вул.&nbspМаршала Бірюзова,&nbsp15</span
Change `&nbsp` to `&nbsp**;**`. You just forgot ';' 
Please fix it everywhere.

![image](https://user-images.githubusercontent.com/82117485/215333420-d8b08284-f37b-4fc1-b690-2c4f7dc59e9e.png)

2023-01-29 16:11 UTC, cutestsun commented on src/partials/hero.html
> +          >Україна, м.&nbspПолтава, вул.&nbspМаршала Бірюзова,&nbsp15</span
fixed the problem

2023-01-29 17:44 UTC, svoits requested changes
please edit hotel hero

2023-01-29 17:44 UTC, svoits commented on src/partials/pages/hotel/hero.html
> +    <p class="hero-text">Смак життя 24/7</p>
there is no 'смак життя 24/7' in hotel.
please delete and change margin between MIMIHO and the buttons

2023-01-29 17:59 UTC, cutestsun commented on src/partials/pages/hotel/hero.html
> +    <p class="hero-text">Смак життя 24/7</p>
the problem was fixed

2023-01-30 17:19 UTC, svoits approved these changes

2023-01-30 17:20 UTC, merged